#!/bin/bash

# Assign pins
DISCON=13

# Set pins 12 and 13 to be outputs driving low to avoid them going high on start up.
# Add the following line to your /boot/config.txt
# gpio=12,13=op,dl
 
# Verify they are set up, else initialize them
test -e /sys/class/gpio/gpio$DISCON ||
  (echo $DISCON > /sys/class/gpio/export \
   && echo out > /sys/class/gpio/gpio$DISCON/direction)

# Set the pin to high, wait 100ms, then set it back to low
echo "1">/sys/class/gpio/gpio$DISCON/value
sleep 0.1
echo "0">/sys/class/gpio/gpio$DISCON/value
