#!/bin/bash

SIR=17
PIR=27
TMR=22
EMT=23
 
test -e /sys/class/gpio/gpio$SIR || 
  (echo $SIR > /sys/class/gpio/export \
   && echo in > /sys/class/gpio/gpio$SIR/direction)
test -e /sys/class/gpio/gpio$PIR ||
  (echo $PIR > /sys/class/gpio/export \
   && echo in > /sys/class/gpio/gpio$PIR/direction)
test -e /sys/class/gpio/gpio$TMR || 
  (echo $TMR > /sys/class/gpio/export \
   && echo in > /sys/class/gpio/gpio$TMR/direction)
test -e /sys/class/gpio/gpio$EMT ||
  (echo $EMT > /sys/class/gpio/export \
   && echo in > /sys/class/gpio/gpio$EMT/direction)


prev_valSIR=$(cat /data/log/prev_valSIR)
prev_valPIR=$(cat /data/log/prev_valPIR)
prev_valTMR=$(cat /data/log/prev_valTMR)
prev_valEMT=$(cat /data/log/prev_valEMT)
  
valSIR=$(cat /sys/class/gpio/gpio$SIR/value)
valPIR=$(cat /sys/class/gpio/gpio$PIR/value)
valTMR=$(cat /sys/class/gpio/gpio$TMR/value)
if [ "$valSIR" == "0" ]; then
    valEMT=$(cat /sys/class/gpio/gpio$EMT/value)
else
    valEMT=$prev_valEMT
fi

echo $valSIR >| /data/log/prev_valSIR
echo $valPIR >| /data/log/prev_valPIR
echo $valTMR >| /data/log/prev_valTMR
if [ "$valSIR" == "0" ]; then
    echo $valEMT >| /data/log/prev_valEMT
fi

 
if [ "$valSIR" == "1" ]; then
    SIR_text="OFF"
else
    SIR_text="ON"
fi

if [ "$valPIR" == "1" ]; then
    PIR_text="IDLE"
else
    PIR_text="TRIG"
fi

if [ "$valTMR" == "1" ]; then
    TMR_text="ON"
else
    TMR_text="OFF"
fi

if [ "$valEMT" == "0" ]; then
    EMT_text="LOW"
else
    EMT_text="OK"
fi

touch /data/log/VMFB.log

dtStamp=$(date +%F_%X)

if [ "$valSIR" != "$prev_valSIR" ]; then
    echo "$dtStamp	IR	$valSIR	$SIR_text">> /data/log/VMFB.log
fi

if [ "$valPIR" != "$prev_valPIR" ]; then
    echo "$dtStamp	PIR	$valPIR	$PIR_text">> /data/log/VMFB.log
fi

if [ "$valTMR" != "$prev_valTMR" ]; then
    echo "$dtStamp	TMR	$valTMR	$TMR_text">> /data/log/VMFB.log
fi

if [ "$valEMT" != "$prev_valEMT" ]; then
    if [ "$valSIR" == "0" ]; then
        echo "$dtStamp	EMT	$valEMT	$EMT_text">> /data/log/VMFB.log
    fi
fi


echo "PIR:$PIR_text|IR:$SIR_text|TMR:$TMR_text|FEED:$EMT_text"
echo 0 1>&2
